### ISSUE TITLE
processmatchqueue.php

### ISSUE THREAD

**Issue by leonhedding** [Microsoft/moodle-local_o365#2]
The sql in this code only works in MySQL. The "LIMIT 0, 100" part of the query needs to be converted to "LIMIT 100" for pgsql.

**Comment by leonhedding** [comment]
As well, I found that the double quotes for mq.errormessage need to be single quotes for pgsql. And finally I had to convert all the {table name} to be mdl_table_name. Now the query works in pgsql and the query match task completes.

**Comment by jamesmcq** [comment]
Thanks for the report - also had this reported at https://tracker.moodle.org/browse/CONTRIB-6100 and a fix is ready for release - expect this next release.

You mentioned you had to convert {table name} to be mdl_table_name - Core Moodle should do this automatically, the {table name} is Moodle's syntax to support different table prefixes (you can change it from mdl_ to something else). 

Once the fix for the two compatibility issues (the double quotes and limit clause) are out in the next release, can you try it without converting {table name}s and see if it works for you? If not there may be something that needs to be addressed in Moodle core.

**Comment by leonhedding** [comment]
Thanks, I was able to revert back tot he {table name} format and get it working. I have another issue to report now with a SQL LIMIT statement, but will report that with another issue.
